### ISSUE TITLE
Can I test all the images in one folder?

### ISSUE THREAD

**Issue by circlebig** [ming053l/DRCT#10]
I don't know how to test my images in one folder.
I will use your pretrained model.
Can you help how can I use your model to train my images?

**Comment by ming053l** [comment]
Hi, 

You can run following script:

`
python drct/test.py -opt options/test/DRCT_SRx4_ImageNet-pretrain.yml`

and, please see the configuration file, 
`
options/test/DRCT_SRx4_ImageNet-pretrain.yml`

First, please change the *dataroot_lq* to your image file folder. And comment out  *dataroot_gt*

```
 test_1:
    name: DIV2K_valid
    type: PairedImageDataset
    #dataroot_gt: "/work/ming0531/DRCT/DRCT/datasets/DIV2K/DIV2K_valid_HR_rotated/"
    dataroot_lq: "/work/ming0531/DRCT/DRCT/datasets/DIV2K/DIV2K_valid_LR_bicubic/"
    io_backend:
      type: disk
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
```

Then, change the location of pretrained model

```
path:
  pretrain_network_g: /work/ming0531/DRCT/models/DRCT-L.pth
  strict_load_g: true
  param_key_g: 'params_ema'

```



You can refer to the following configuration
```
name: test_DRCT-L_SRx4_NTIRE_rotate_270_300000_1_test
model_type: DRCTModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

datasets:

  test_1:
    name: DIV2K_valid
    type: SingleImageDataset
    #dataroot_gt: "/work/ming0531/DRCT/data/DIV2K/DIV2K_valid_HR_rotated/rotated_270/"
    dataroot_lq: "/work/ming0531/DRCT/data/test/DIV2K_test_LR_bicubic/rotated_270/"
    io_backend:
      type: disk
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1

  # test_2:  # the 2nd test dataset
  #   name: Set14
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/Set14/GTmod4
  #   dataroot_lq: ./datasets/Set14/LRbicx4
  #   io_backend:
  #     type: disk

  # test_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/urban100/GTmod4
  #   dataroot_lq: ./datasets/urban100/LRbicx4
  #   io_backend:
  #     type: disk

  # test_4:
  #    name: BSDS100
  #    type: PairedImageDataset
  #    dataroot_gt: ./datasets/BSDS100/GTmod4
  #    dataroot_lq: ./datasets/BSDS100/LRbicx4
  #    io_backend:
  #      type: disk

  # test_5:
  #     name: Manga109
  #     type: PairedImageDataset
  #     dataroot_gt: ./datasets/manga109/GTmod4
  #     dataroot_lq: ./datasets/manga109/LRbicx4
  #     io_backend:
  #       type: disk

# network structures
network_g:
  type: DRCT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  gc: 32
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
# path
path:
  pretrain_network_g : "/work/ming0531/DRCT/experiments/train_DRCT-L_SRx4_NTIRE_1e5_resume_archived_20240315_162311/models/net_g_250000.pth"
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name
```
